[package]
name = "lampod"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "^1.29.1", features = ["rt-multi-thread", "parking_lot"] }
rgb-lampo-common = { package = "lampo-common", path = "../lampo-common", features = ["rgb"], optional = true }
lampo-common = { path = "../lampo-common", features = ["vanilla"], optional = true }
lampo-jsonrpc = { path = "../lampo-jsonrpc", optional = true }
lampo-client = { path = "../lampo-client", optional = true }
log = "0.4.17"
time = "0.3.13"
futures = "0.3.28"
crossbeam-channel = "0.5.8"
once_cell = "1.17.1"
async-trait = "0.1.68"

[features]
default = []
vanilla = ["lampo-common", "lampo-jsonrpc", "lampo-client"]
rgb = ["rgb-lampo-common"]