[package]
name = "lampo-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys", features = ["max_level_trace"], optional = true }
lightning-block-sync = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys" }
lightning-persister = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys" }
lightning-background-processor = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys" }
lightning-net-tokio = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys" }
lightning-rapid-gossip-sync = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys" }
lightning-invoice = { git = "https://github.com/vincenzopalazzo/rust-lightning.git", branch = "macros/allow-to-inject-channels-keys" }
bitcoin = { version = "0.30.2", features = ["serde"] }
clightningrpc-conf = { git = "https://github.com/laanwj/cln4rust.git", branch = "master" }
crossbeam-channel = "0.5.8"
anyhow = "1.0.70"
colored = "1.9"
log = { version = "0.4", features = ["std"] }
chrono = { version = "0.4", features = ["std"], default-features = false }
serde_json = "1.0"
serde = "1.0"
hex = "0.4.3"

# RGB dependencies
rgb-lightning = { version = "0.0.118", package = "lightning", git = "https://github.com/RGB-Tools/rust-lightning", optional = true }
# rgb-lightning-background-processor = { package = "lightning-background-processor", features = ["futures"], git = "https://github.com/RGB-Tools/rust-lightning", branch="rgb", optional = true }
# rgb-lightning-invoice = { package = "lightning-invoice", git = "https://github.com/RGB-Tools/rust-lightning", branch="rgb", optional = true }
# rgb-lightning-persister = { package = "lightning-persister", git = "https://github.com/RGB-Tools/rust-lightning", branch="rgb", optional = true }

# RGB-related deps
amplify = "=4.5.0"
bp-core = "=0.10.11"
rgb-lib = { git = "https://github.com/RGB-Tools/rgb-lib", branch = "rln_v0.10" }
rgb-std = "=0.10.9"
rgb-wallet = "=0.10.9"
rgb_core = { package = "rgb-core", version = "=0.10.8" }
strict_encoding = "=2.6.1"
strict_types = "=1.6.3"
# bitcoin_30 = { package = "bitcoin", version = "0.30.0", optional = true }

[features]
default = ["lightning"]
rgb = ["rgb-lightning" ]